
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logisticsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    flyway:
     enabled: true
     baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG

distance:
  api:
    url: http://localhost:8080/mock/distance